# .github/workflows/ai-reviewer.yml

name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.head_ref }}

      # Step 1: Authenticate to Google Cloud. This creates the credentials file.
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # Step 2: Set up the Google Cloud SDK. This will now find and use the credentials.
      - name: 'Set up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Run AI Review'
        run: |
          # This is a placeholder for the review script.
          # It will be replaced with the actual review logic later.
          REVIEW_COMMENT="This is a test comment from the AI Reviewer. The connection to Google Cloud is successful."

          gh pr comment ${{ github.event.pull_request.number }} --body "$REVIEW_COMMENT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
