name: Sync Documentation to GCS

on:
  push:
    branches:
      - main
    paths:
      - 'Instructions/**'

permissions:
  contents: read
  id-token: write

jobs:
  sync-to-gcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print OIDC Token Audience
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken();
            const [header, payload] = token.split('.').slice(0, 2).map(part => Buffer.from(part, 'base64').toString('utf8'));
            console.log('OIDC Token header:', header);
            console.log('OIDC Token payload:', payload);
            const payloadObj = JSON.parse(payload);
            console.log('OIDC Token Audience (aud):', payloadObj.aud);

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          audience: https://github.com/AdamIsherwood

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Sync files to Google Cloud Storage
        run: |
          echo "Syncing the Instructions folder to the GCS bucket..."
          gcloud storage rsync Instructions gs://avar-assistant-app_1753569803517 --recursive --delete-unmatched-destination-objects
