# .github/workflows/sync-docs-to-gcs.yml

name: Sync Documentation to GCS

# This workflow triggers ONLY on a push to the main branch.
# This means it will run every time you merge a pull request.
on:
  push:
    branches:
      - main
    paths:
      - 'Instructions/**' # Only run if files inside the Instructions folder change

permissions:
  contents: read
  id-token: write

jobs:
  sync-to-gcs:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'

      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      
      - name: 'Set up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 'Sync files to Google Cloud Storage'
        run: |
          echo "Syncing the Instructions folder to the GCS bucket..."
          
          # The 'rsync' command is perfect for this. It makes the destination
          # (the GCS bucket) an exact mirror of the source (the local folder).
          # The -d flag also deletes any files in the bucket that are no longer
          # in the GitHub repository, keeping everything perfectly clean.
          gcloud storage rsync Instructions gs://avar-assistant-app_1753569803517 --recursive --delete-unmatched-destination-objects

      - name: Print OIDC Token
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL"
